source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'Idea Screener' do
pod 'Alamofire'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'GoogleSignIn'
pod 'Stripe'
pod 'AFNetworking'

end

